-- 1. Get All Orders by a User (Customer / Vendor)

-- From Customer
SELECT o.orderId,
       o.orderDate,
       o.totalAmount,
       u.userId,
       u.FullName
FROM orders o
  JOIN users u ON o.userId = u.userId
WHERE o.userId = 1002;

-- From vendor
SELECT o.orderId,
       o.orderDate,
       o.totalAmount,
       v.vendorId,
       v.vendorName
FROM orders o
  JOIN vendors v ON o.vendorId = v.vendorId
WHERE v.vendorId = 3;


-- 2. Order Summary with Items
SELECT o.OrderID,
       p.Name,
       oi.Quantity,
       oi.Price
FROM Orders o
  JOIN OrderItems oi ON o.OrderID = oi.OrderID
  JOIN Products p ON p.ProductID = oi.ProductID;


--3. Total Revenue Generated by Each Vendor
SELECT v.VendorName,
       SUM(o.TotalAmount) TotalRevenue
FROM Orders o
  JOIN Vendors v ON o.VendorID = v.VendorID
GROUP BY v.VendorName;

--4. Top 5 Bestselling Products
SELECT p.Name,
       SUM(oi.Quantity) AS TotalSold
FROM OrderItems oi
  JOIN Products p ON oi.ProductID = p.ProductID
GROUP BY p.Name
ORDER BY TotalSold DESC FETCH FIRST 5 ROWS ONLY;

--5. Average Product Rating
SELECT p.Name,
       AVG(r.Rating) AS "Avg. Rating"
FROM Reviews r
  JOIN Products p ON r.ProductID = p.ProductID
GROUP BY p.Name
ORDER BY "Avg. Rating" DESC;

--6. Delivery Status of a Particular Order
SELECT o.OrderID,
       s.StatusName,
       ds.UpdatedAt
FROM DeliveryStatus ds
  JOIN Status s ON ds.StatusID = s.StatusID
  JOIN Orders o ON o.OrderID = ds.OrderID
WHERE o.OrderID = 4;

--7. Daily Order Count
SELECT TRUNC(OrderDate) AS OrderDay,
       COUNT(*) AS TotalOrders
FROM Orders
GROUP BY TRUNC(OrderDate);

--8. Top 5 Customers by Order Value
SELECT u.FullName,
       SUM(o.TotalAmount) AS TotalSpent
FROM Orders o
  JOIN Users u ON o.UserID = u.UserID
GROUP BY u.FullName
ORDER BY TotalSpent DESC FETCH FIRST 5 ROWS ONLY;

--9. Low Stock Products Per Vendor (below 20 units)
SELECT v.VendorName,
       p.Name,
       i.QuantityAvailable
FROM Inventory i
  JOIN Vendors v ON i.VendorID = v.VendorID
  JOIN Products p ON i.ProductID = p.ProductID
WHERE i.QuantityAvailable < 20
ORDER BY i.QuantityAvailable;

--10. Search Products by Keyword Milk (Flexible Query)
SELECT * 
FROM Products
WHERE Name LIKE '%1%';